# Generated by Django 2.2.2 on 2019-06-10 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solovey',
            name='id',
            field=models.BigAutoField(db_column='id', primary_key=True, serialize=False),
        ),
    ]
