# Generated by Django 2.2.2 on 2019-06-11 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20190610_0609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solovey',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
